name: Deploy Cloud Functions
on:
  push:
    branches:
          - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Install npm packages
        run: npm install
      - name: typecheck
        run: npm run build
      - id: "firebase-test1"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "firebase-test1"
          runtime: "python310"
          region: asia-northeast1

          entry_point: create_code
          ingress_settings: ALLOW_ALL
