name: Deploy Cloud Functions
on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    env:
      REGION: asia-northeast1
      ENTRY_POINT: create_data
      runtime: python310
#       TOPIC: トリガーとなるPubSubのトピックID
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@main
        with:
          project_id: fresh-effort-343112
          service_account_email: gcf-deploy@fresh-effort-343112.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy Functions
        run: |
          gcloud functions deploy firebase-test1 --region=${REGION} --entry-point ${ENTRY_POINT} --runtime ${runtime}
