name: Deploy Cloud Funcstions

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Cloud SDK
      uses: google-github-actions/deploy-cloud-functions@master
      with:
        project_id: fresh-effort-343112
        service_account_email: gcf-deploy@fresh-effort-343112.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        ## Functionsにデプロイする関数名
        entry_point: main
        region: asia-northeast1
        runtime: python39 
        
#     - name: Deploy Functions
#         run: gcloud functions deploy firebase-test1 --source ./ --region=${REGION} --entry-point ${ENTRY_POINT} --runtime python310

# name: Deploy Cloud Functions
# on:
#   # Push時に実行
#   workflow_dispatch:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     name: Deploy Functions
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - id: deploy
#         uses: google-github-actions/deploy-cloud-functions@main
#         with:
#           ## Google Cloud Functions上での名前
#           name: firebase-test1

#           ## runtimeの設定．今回はpythonを指定
#           runtime: python310

#           ## GCPの鍵．
#           project_id: fresh-effort-343112
#           service_account_email: gcf-deploy@fresh-effort-343112.iam.gserviceaccount.com
#           service_account_key: ${{ secrets.GCP_SA_KEY }}

#           ## Functionsにデプロイする関数名
#           entry_point: main

#           ## Regionの指定．指定しないとエラーが出るかも?
#           region: asia-northeast1

#           ## Schedulerと組み合わせたいので、FunctionsのトリガータイプをPub/Subにする
# #           event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
# #           event_trigger_resource: projects/${{ secrets.gcp_project_id }}/topics/my-pubsub-topic

#           ## Functions上の環境変数を指定．
#           ## Discordにメッセージを送りたいのでWebhookを設定。
# #           env_vars: DISCORD_WEBHOOK_URL=${{ secrets.discord }}
