# This is a basic workflow to help you get started with Actions

name: Deploy Cloud Functions
on:
  push:
    branches: [ "main" ]
    
jobs:
  Deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'firebase-test1'
        runtime: 'python310'
        entry_point: 'create_data'
        region: 'asia-northeast1'
        project_id: 'fresh-effort-343112'
      
