name: Deploy Cloud Functions

on:
  push:
    branches: [ "main" ]
    

jobs:
  build-deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    env:
      REGION: asia-northeast1

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          # OSSであれば project_id や service_account_email もsecretsに入れるのが良いでしょう
          project_id: fresh-effort-343112
          service_account_email: gcf-deploy@fresh-effort-343112.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy Functions
        run: |
          gcloud functions deploy firebase-test1 --source ./src/firebase-test1 --region=${REGION}
