name: Deploy Cloud Functions
on:
  # Push時に実行
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          ## Google Cloud Functions上での名前
          name: firebase-test1 

          ## runtimeの設定．今回はpythonを指定
          runtime: python310 

          ## GCPの鍵．
          credentials: ${{ secrets.gcp_credentials }}　

          ## Functionsにデプロイする関数名
          entry_point: create_data

          ## Regionの指定．指定しないとエラーが出るかも?
          region: asia-northeast1
