name: Deploy Cloud Functions
on:
  # Push時に実行
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          ## Google Cloud Functions上での名前
          name: firebase-test1 

          ## runtimeの設定．今回はpythonを指定
          runtime: python39 

          ## GCPの鍵．
          credentials: ${{ secrets.gcp_credentials }}　

          ## Functionsにデプロイする関数名
          entry_point: create_data

          ## Regionの指定．指定しないとエラーが出るかも?
          region: asia-northeast1

          ## Schedulerと組み合わせたいので、FunctionsのトリガータイプをPub/Subにする
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.gcp_project_id }}/topics/my-pubsub-topic

          ## Functions上の環境変数を指定．
          ## Discordにメッセージを送りたいのでWebhookを設定。
          env_vars: DISCORD_WEBHOOK_URL=${{ secrets.discord }}
