name: Deploy Cloud Functions
on:
  push:
    branches:
      - "main"
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'firebase-test1'
        runtime: 'python310'
        entry_point: create_data
        region: asia-northeast1
        description: crud trigger
        ingress_settings: ALLOW_ALL

      
